version: "3"

services:
  fuseki:
    image: ghcr.io/zazuko/fuseki-geosparql:v2.1
    ports:
      - 3030:3030
    environment:
      - ADMIN_PASSWORD=password
      - ENABLE_DATA_WRITE=true
      - ENABLE_UPDATE=true
      - ENABLE_UPLOAD=true
    volumes:
      - ./test/fuseki.ttl:/fuseki/config.ttl